import { ChestTier, ItemRarity, LootChestConfig, LootItem, UnboxResult } from '../types/casino';

export const RARITY_CONFIG: Record<
  ItemRarity,
  {
    label: string;
    textColor: string;
    bgColor: string;
    borderColor: string;
    shadowColor: string;
    glowClass: string;
  }
> = {
  common: {
    label: 'Common',
    textColor: 'text-stone-400',
    bgColor: 'bg-stone-800/80',
    borderColor: 'border-stone-600',
    shadowColor: 'rgba(120, 113, 108, 0.3)',
    glowClass: 'shadow-stone-700/30',
  },
  rare: {
    label: 'Rare',
    textColor: 'text-sky-400',
    bgColor: 'bg-sky-950/70',
    borderColor: 'border-sky-500',
    shadowColor: 'rgba(14, 165, 233, 0.4)',
    glowClass: 'shadow-sky-500/40',
  },
  epic: {
    label: 'Epic',
    textColor: 'text-purple-400',
    bgColor: 'bg-purple-950/70',
    borderColor: 'border-purple-500',
    shadowColor: 'rgba(168, 85, 247, 0.4)',
    glowClass: 'shadow-purple-500/40',
  },
  legendary: {
    label: 'Legendary',
    textColor: 'text-amber-300',
    bgColor: 'bg-amber-950/80',
    borderColor: 'border-amber-400',
    shadowColor: 'rgba(251, 191, 36, 0.6)',
    glowClass: 'shadow-amber-400/50',
  },
  mythic: {
    label: 'Mythic',
    textColor: 'text-rose-400',
    bgColor: 'bg-rose-950/90',
    borderColor: 'border-rose-500',
    shadowColor: 'rgba(244, 63, 94, 0.7)',
    glowClass: 'shadow-rose-500/60',
  },
};

export const LOOT_CHESTS: Record<ChestTier, LootChestConfig> = {
  squire: {
    id: 'squire',
    name: "Squire's Wooden Casket",
    subtitle: 'Tier I • Humble Beginnings',
    category: 'relics',
    cost: 10,
    badgeColor: 'bg-amber-800/30 text-amber-300 border-amber-700/50',
    borderColor: 'border-amber-800/80 hover:border-amber-600',
    glowColor: 'shadow-[0_0_25px_rgba(180,83,9,0.25)]',
    description: 'Entry-level casket containing common armaments and hidden silver coins. Low risk.',
    topMultiplier: 100,
    items: [
      {
        id: 'sq-1',
        name: 'Rusted Iron Dagger',
        rarity: 'common',
        multiplier: 0.2,
        icon: 'Sword',
        weight: 4900,
        description: 'Blunt blade discarded by royal infantry.',
      },
      {
        id: 'sq-2',
        name: "Peasant's Copper Mug",
        rarity: 'common',
        multiplier: 0.5,
        icon: 'Coffee',
        weight: 3200,
        description: 'Dented tavern tankard carrying old copper.',
      },
      {
        id: 'sq-3',
        name: "Archer's Quiver",
        rarity: 'common',
        multiplier: 1.5,
        icon: 'Target',
        weight: 1300,
        description: 'Leather quiver with fletched hunting arrows.',
      },
      {
        id: 'sq-4',
        name: 'Steel Shortsword',
        rarity: 'rare',
        multiplier: 4.0,
        icon: 'Shield',
        weight: 460,
        description: 'Refined castle steel forged by the royal armorer.',
      },
      {
        id: 'sq-5',
        name: "Knight's Silver Signet",
        rarity: 'rare',
        multiplier: 10.0,
        icon: 'Gem',
        weight: 110,
        description: 'Engraved crest with pure sterling silver value.',
      },
      {
        id: 'sq-6',
        name: 'Banner of Valor',
        rarity: 'epic',
        multiplier: 30.0,
        icon: 'Flag',
        weight: 25,
        description: 'Silk crest hoisted during the First Crusade.',
      },
      {
        id: 'sq-7',
        name: 'Gilded Crossbow',
        rarity: 'legendary',
        multiplier: 100.0,
        icon: 'Sparkles',
        weight: 5,
        description: 'Masterwork weapon inlaid with pure yellow gold.',
      },
    ],
  },
  knight: {
    id: 'knight',
    name: "Knight's Iron Strongbox",
    subtitle: 'Tier II • Vanguard Bounty',
    category: 'relics',
    cost: 50,
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/50',
    borderColor: 'border-slate-500/80 hover:border-slate-400',
    glowColor: 'shadow-[0_0_25px_rgba(148,163,184,0.3)]',
    description: 'Reinforced iron strongbox carried into siege battlefields. Balanced risk and reward.',
    topMultiplier: 250,
    items: [
      {
        id: 'kn-1',
        name: 'Dull Siege Halberd',
        rarity: 'common',
        multiplier: 0.2,
        icon: 'Sword',
        weight: 4900,
        description: 'Standard issue polearm with weathered wood.',
      },
      {
        id: 'kn-2',
        name: 'Chainmail Coif',
        rarity: 'common',
        multiplier: 0.5,
        icon: 'Shield',
        weight: 3200,
        description: 'Interlinked iron rings worn under helmets.',
      },
      {
        id: 'kn-3',
        name: 'Templar Holy Cross',
        rarity: 'rare',
        multiplier: 1.8,
        icon: 'Sparkles',
        weight: 1250,
        description: 'Silver pendant blessed in the cathedral.',
      },
      {
        id: 'kn-4',
        name: 'Damascus Broadsword',
        rarity: 'rare',
        multiplier: 3.5,
        icon: 'Flame',
        weight: 510,
        description: 'Folded steel blade with wavy water patterns.',
      },
      {
        id: 'kn-5',
        name: "Paladin's Tower Shield",
        rarity: 'epic',
        multiplier: 10.0,
        icon: 'Shield',
        weight: 115,
        description: 'Heavy barrier inscribed with warding runes.',
      },
      {
        id: 'kn-6',
        name: 'Chalice of Camelot',
        rarity: 'epic',
        multiplier: 25.0,
        icon: 'Crown',
        weight: 20,
        description: 'Goblet said to bestow relentless luck.',
      },
      {
        id: 'kn-7',
        name: "King's Guard Helm",
        rarity: 'legendary',
        multiplier: 75.0,
        icon: 'Crown',
        weight: 4,
        description: 'Ceremonial crest helmet laced with gold leaf.',
      },
      {
        id: 'kn-8',
        name: 'Excalibur Shard',
        rarity: 'mythic',
        multiplier: 250.0,
        icon: 'Sparkles',
        weight: 1,
        description: 'Glowing fragment of the legendary sword in the stone.',
      },
    ],
  },
  royal: {
    id: 'royal',
    name: 'Royal Gilded Sarcophagus',
    subtitle: 'Tier III • Sovereign Treasury',
    category: 'relics',
    cost: 150,
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/50',
    borderColor: 'border-amber-500/80 hover:border-amber-400',
    glowColor: 'shadow-[0_0_30px_rgba(245,158,11,0.35)]',
    description: 'Gold-plated royal chest containing court treasures, coronation rings, and holy relics.',
    topMultiplier: 500,
    items: [
      {
        id: 'ro-1',
        name: 'Gilded Feast Goblet',
        rarity: 'rare',
        multiplier: 0.25,
        icon: 'Coffee',
        weight: 5300,
        description: 'Courtware crafted for banquets in the Great Hall.',
      },
      {
        id: 'ro-2',
        name: 'Emerald Queen Ring',
        rarity: 'rare',
        multiplier: 0.6,
        icon: 'Gem',
        weight: 3200,
        description: 'Brilliant green Colombian beryl set in platinum.',
      },
      {
        id: 'ro-3',
        name: 'Scepter of Monarchs',
        rarity: 'epic',
        multiplier: 1.8,
        icon: 'Sparkles',
        weight: 1100,
        description: 'Staff of command crowned with blue sapphire.',
      },
      {
        id: 'ro-4',
        name: 'Coronation Diadem',
        rarity: 'epic',
        multiplier: 5.0,
        icon: 'Crown',
        weight: 340,
        description: 'Royal headpiece encrusted with royal rubies.',
      },
      {
        id: 'ro-5',
        name: "Archangel's Golden Lance",
        rarity: 'legendary',
        multiplier: 20.0,
        icon: 'Flame',
        weight: 52,
        description: 'Blinding spear blessed by the high patriarch.',
      },
      {
        id: 'ro-6',
        name: 'Arthurian Holy Grail',
        rarity: 'legendary',
        multiplier: 75.0,
        icon: 'Crown',
        weight: 7,
        description: 'The sacred vessel of eternal grace and wealth.',
      },
      {
        id: 'ro-7',
        name: 'Crown Jewels of Albion',
        rarity: 'mythic',
        multiplier: 500.0,
        icon: 'Sparkles',
        weight: 1,
        description: 'The supreme royal regalia of the entire realm.',
      },
    ],
  },
  mythic: {
    id: 'mythic',
    name: "Dragonlord's Imperial Vault",
    subtitle: 'Tier IV • Ancient Dragonfire',
    category: 'relics',
    cost: 500,
    badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/50',
    borderColor: 'border-rose-500/80 hover:border-rose-400',
    glowColor: 'shadow-[0_0_35px_rgba(244,63,94,0.4)]',
    description: 'Forged in dragon magma. Extreme volatility with top jackpot multipliers up to 2,500x!',
    topMultiplier: 2500,
    items: [
      {
        id: 'dr-1',
        name: 'Molten Dragon Scale',
        rarity: 'epic',
        multiplier: 0.25,
        icon: 'Shield',
        weight: 5800,
        description: 'Heat-radiating scale torn from an elder drake.',
      },
      {
        id: 'dr-2',
        name: "Wyrm Slayer's Claymore",
        rarity: 'epic',
        multiplier: 0.5,
        icon: 'Sword',
        weight: 3100,
        description: 'Heavy broadblade drenched in primordial dragon blood.',
      },
      {
        id: 'dr-3',
        name: 'Phoenix Feather Amulet',
        rarity: 'legendary',
        multiplier: 1.8,
        icon: 'Flame',
        weight: 850,
        description: 'Pendant burning with everlasting golden flames.',
      },
      {
        id: 'dr-4',
        name: 'Orb of Eternal Pyres',
        rarity: 'legendary',
        multiplier: 4.5,
        icon: 'Sparkles',
        weight: 215,
        description: 'Concentrated magical core from the Volcano of Doom.',
      },
      {
        id: 'dr-5',
        name: 'Dragon Heart Blood Ruby',
        rarity: 'mythic',
        multiplier: 25.0,
        icon: 'Gem',
        weight: 30,
        description: 'A fist-sized jewel pulsing with volcanic lifeforce.',
      },
      {
        id: 'dr-6',
        name: 'Imperial Dragon Crown',
        rarity: 'mythic',
        multiplier: 100.0,
        icon: 'Crown',
        weight: 4,
        description: 'Crown forged from black obsidian and dragon horns.',
      },
      {
        id: 'dr-7',
        name: 'Ancient Wyrm God Relic',
        rarity: 'mythic',
        multiplier: 2500.0,
        icon: 'Sparkles',
        weight: 1,
        description: 'The supreme primordial treasure of the dragons.',
      },
    ],
  },
  gem_emerald: {
    id: 'gem_emerald',
    name: 'Emerald Geode Vault',
    subtitle: 'Gemstone Tier I • Forest Crystals',
    category: 'gems',
    cost: 25,
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/50',
    borderColor: 'border-emerald-600/80 hover:border-emerald-400',
    glowColor: 'shadow-[0_0_25px_rgba(16,185,129,0.25)]',
    description: 'Crystalline geodes harvested from enchanted groves. Jade talismans, malachite shards, and royal emeralds.',
    topMultiplier: 150,
    items: [
      {
        id: 'ge-1',
        name: 'Raw Malachite Shard',
        rarity: 'common',
        multiplier: 0.25,
        icon: 'Gem',
        weight: 4800,
        description: 'Banded green copper mineral chip.',
      },
      {
        id: 'ge-2',
        name: 'Polished Jade Pebble',
        rarity: 'common',
        multiplier: 0.5,
        icon: 'Gem',
        weight: 3300,
        description: 'Smooth river stone talisman carrying subtle fortune.',
      },
      {
        id: 'ge-3',
        name: 'Moss Agate Talisman',
        rarity: 'common',
        multiplier: 1.5,
        icon: 'Sparkles',
        weight: 1300,
        description: 'Translucent chalcedony laced with green dendritic filaments.',
      },
      {
        id: 'ge-4',
        name: 'Forest Emerald Cabochon',
        rarity: 'rare',
        multiplier: 4.0,
        icon: 'Gem',
        weight: 480,
        description: 'Vivid green beryl cut and polished for royal rings.',
      },
      {
        id: 'ge-5',
        name: 'Jade Dragon Carving',
        rarity: 'rare',
        multiplier: 10.0,
        icon: 'Shield',
        weight: 95,
        description: 'Imperial nephrite sculpture blessed with ancient power.',
      },
      {
        id: 'ge-6',
        name: 'Heart of Yggdrasil',
        rarity: 'epic',
        multiplier: 35.0,
        icon: 'Gem',
        weight: 22,
        description: 'Pulsing tree-gem nurtured by world roots.',
      },
      {
        id: 'ge-7',
        name: 'Sovereign Emerald Diadem',
        rarity: 'legendary',
        multiplier: 150.0,
        icon: 'Crown',
        weight: 3,
        description: 'High queen crown adorned with seven radiant Colombian emeralds.',
      },
    ],
  },
  gem_sapphire: {
    id: 'gem_sapphire',
    name: 'Sapphire Astral Reliquary',
    subtitle: 'Gemstone Tier II • Cobalt Stars',
    category: 'gems',
    cost: 75,
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/50',
    borderColor: 'border-blue-600/80 hover:border-blue-400',
    glowColor: 'shadow-[0_0_25px_rgba(59,130,246,0.25)]',
    description: 'Forged in mountaintop observatories. Lapis lazuli, astral starlight prisms, and star sapphires.',
    topMultiplier: 250,
    items: [
      {
        id: 'sa-1',
        name: 'Lapis Lazuli Fragment',
        rarity: 'common',
        multiplier: 0.2,
        icon: 'Gem',
        weight: 5100,
        description: 'Deep cobalt stone with flecks of golden pyrite.',
      },
      {
        id: 'sa-2',
        name: 'Sky Quartz Crystal',
        rarity: 'common',
        multiplier: 0.5,
        icon: 'Gem',
        weight: 3100,
        description: 'Translucent blue crystal prism capturing moonlight.',
      },
      {
        id: 'sa-3',
        name: 'Cobalt Arcane Prism',
        rarity: 'rare',
        multiplier: 1.8,
        icon: 'Sparkles',
        weight: 1220,
        description: 'Focusing lens used by royal court sorcerers.',
      },
      {
        id: 'sa-4',
        name: 'Midnight Star Sapphire',
        rarity: 'rare',
        multiplier: 4.0,
        icon: 'Gem',
        weight: 470,
        description: 'Six-rayed asterism gem glowing in velvet darkness.',
      },
      {
        id: 'sa-5',
        name: 'Archmage Blue Topaz',
        rarity: 'epic',
        multiplier: 12.0,
        icon: 'Gem',
        weight: 90,
        description: 'Superheated radiant crystal pulsating with mana.',
      },
      {
        id: 'sa-6',
        name: 'Eye of the Leviathan',
        rarity: 'epic',
        multiplier: 40.0,
        icon: 'Shield',
        weight: 18,
        description: 'Ancient fossilized deep-sea pearl radiating tidal luck.',
      },
      {
        id: 'sa-7',
        name: 'Celestial Astral Supernova',
        rarity: 'legendary',
        multiplier: 250.0,
        icon: 'Sparkles',
        weight: 2,
        description: 'Fallen star fragment that shines with infinite cosmic luster.',
      },
    ],
  },
  gem_ruby: {
    id: 'gem_ruby',
    name: 'Dragon Ruby Cavern',
    subtitle: 'Gemstone Tier III • Primordial Bloodstones',
    category: 'gems',
    cost: 250,
    badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/50',
    borderColor: 'border-rose-600/80 hover:border-rose-400',
    glowColor: 'shadow-[0_0_30px_rgba(244,63,94,0.3)]',
    description: 'Mined from dormant magma chambers beneath dragon lairs. Pure carmine ruby crystals radiating primal heat.',
    topMultiplier: 600,
    items: [
      {
        id: 'ru-1',
        name: 'Cinnabar Ore Chaff',
        rarity: 'common',
        multiplier: 0.25,
        icon: 'Gem',
        weight: 5200,
        description: 'Volcanic sediment with rich vermilion traces.',
      },
      {
        id: 'ru-2',
        name: 'Carnelian Blood Pebble',
        rarity: 'common',
        multiplier: 0.5,
        icon: 'Gem',
        weight: 3150,
        description: 'Warm reddish-orange agate infused with furnace ash.',
      },
      {
        id: 'ru-3',
        name: 'Scorchstone Pyrite',
        rarity: 'rare',
        multiplier: 1.6,
        icon: 'Flame',
        weight: 1150,
        description: 'Fiery metallic crystal that strikes sparks on armor.',
      },
      {
        id: 'ru-4',
        name: 'Crimson Dragon Eye Ruby',
        rarity: 'epic',
        multiplier: 5.0,
        icon: 'Gem',
        weight: 410,
        description: 'Pigeon blood Burmese ruby reflecting slit dragon pupils.',
      },
      {
        id: 'ru-5',
        name: 'Volcanic Fire Garnet',
        rarity: 'epic',
        multiplier: 15.0,
        icon: 'Flame',
        weight: 78,
        description: 'Deep crimson dodecahedron crystal from the mantle abyss.',
      },
      {
        id: 'ru-6',
        name: 'Heart of the Phoenix',
        rarity: 'legendary',
        multiplier: 60.0,
        icon: 'Flame',
        weight: 11,
        description: 'Ever-burning blood jewel reborn from the ashes of time.',
      },
      {
        id: 'ru-7',
        name: 'Primordial Sunfire Ruby',
        rarity: 'mythic',
        multiplier: 600.0,
        icon: 'Sparkles',
        weight: 1,
        description: 'The ancient sovereign flame-gem that kindled the first dragonfire.',
      },
    ],
  },
  gem_diamond: {
    id: 'gem_diamond',
    name: 'Imperial Diamond Vault',
    subtitle: 'Gemstone Tier IV • Apex of Gemology',
    category: 'gems',
    cost: 1000,
    badgeColor: 'bg-cyan-400/20 text-cyan-300 border-cyan-400/50',
    borderColor: 'border-cyan-400/80 hover:border-cyan-300',
    glowColor: 'shadow-[0_0_35px_rgba(6,182,212,0.35)]',
    description: 'The absolute zenith of wealth. Flawless D-color diamonds, refractive prisms, and the sovereign Koh-i-Noor.',
    topMultiplier: 1500,
    items: [
      {
        id: 'di-1',
        name: 'Industrial Carbonado Shard',
        rarity: 'common',
        multiplier: 0.2,
        icon: 'Gem',
        weight: 5350,
        description: 'Opaque black diamond polycrystalline conglomerate.',
      },
      {
        id: 'di-2',
        name: 'Rough Kimberlite Core',
        rarity: 'common',
        multiplier: 0.5,
        icon: 'Gem',
        weight: 3100,
        description: 'Deep mantle volcanic pipe containing unpolished stones.',
      },
      {
        id: 'di-3',
        name: 'Princess Cut Brilliant',
        rarity: 'rare',
        multiplier: 1.8,
        icon: 'Gem',
        weight: 1150,
        description: 'Flawless square-cut diamond radiating prismatic dispersion.',
      },
      {
        id: 'di-4',
        name: 'Radiant Blue Hope Diamond',
        rarity: 'epic',
        multiplier: 5.0,
        icon: 'Gem',
        weight: 340,
        description: 'Historic deep-blue crystal steeped in royal intrigue.',
      },
      {
        id: 'di-5',
        name: 'Sovereign Pink Star Diamond',
        rarity: 'legendary',
        multiplier: 20.0,
        icon: 'Gem',
        weight: 52,
        description: 'Vivid fancy pink oval diamond prized by sovereign monarchs.',
      },
      {
        id: 'di-6',
        name: 'The Great Star of Africa',
        rarity: 'mythic',
        multiplier: 150.0,
        icon: 'Crown',
        weight: 7,
        description: 'The premier 530-carat gem set into the Sovereign Sceptre.',
      },
      {
        id: 'di-7',
        name: 'Eternal Celestial Koh-i-Noor',
        rarity: 'mythic',
        multiplier: 1500.0,
        icon: 'Sparkles',
        weight: 1,
        description: 'Mountain of Light: the legendary gem of world conquerors.',
      },
    ],
  },
};

// Weighted random selection of an item from a chest
export function rollLootItem(chestTier: ChestTier): LootItem {
  const chest = LOOT_CHESTS[chestTier];
  const totalWeight = chest.items.reduce((sum, item) => sum + item.weight, 0);
  let randomVal = Math.random() * totalWeight;

  for (const item of chest.items) {
    if (randomVal < item.weight) {
      return item;
    }
    randomVal -= item.weight;
  }

  return chest.items[0];
}

// Generate the 40-item horizontal spinning reel with the winning item fixed at targetIndex (e.g. index 32)
export function generateSpinReel(
  chestTier: ChestTier,
  winningItem: LootItem,
  totalItems: number = 40,
  targetIndex: number = 32
): LootItem[] {
  const reel: LootItem[] = [];

  for (let i = 0; i < totalItems; i++) {
    if (i === targetIndex) {
      reel.push(winningItem);
    } else {
      // Use authentic weighted distribution so reel visuals accurately reflect rarity
      reel.push(rollLootItem(chestTier));
    }
  }

  return reel;
}
